### PR TITLE
refactor: :recycle: move `FeedLink` to `components/Feed`

### PR DESCRIPTION
**Pull request by kewinzaq1**

### CODE REVIEW

**Review by ritmillio — APPROVED** [review]
LGTM

**Review by ritmillio — CHANGES_REQUESTED** [review]
remove analytics from FeedLink -> onpress

**Comment by kewinzaq1** [comment]
> remove analytics from FeedLink -> onpress

@ritmillio Why?

**Comment by ritmillio** [comment]
> > remove analytics from FeedLink -> onpress
> 
> @ritmillio Why?

segment got removed from the basic template

**Review by ritmillio — APPROVED** [review]
thanks for the removal

**Pull request merged**
